name: 'Conventional Commits Linter'

description: 'Lint commits messages.'

branding:
  icon: check-circle
  color: gray-dark

inputs:
  git-range:
    description: 'Range of commits.'
    required: false
    default: 'HEAD'
  conventional-regex:
    description: 'Regex used to determine if a commit is conventional'
    required: false
    default: "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([[:alnum:]._-]+\))?(!)?: ([[:alnum:]])+([[:space:][:print:]]*)"
  conventional-regex-patch:
    description: 'Regex used to determine if a commit is conventional'
    required: false
    default: "^(fix){1}(\([[:alnum:]._-]+\))?: ([[:alnum:]])+([[:space:][:print:]]*)"
  conventional-regex-minor:
    description: 'Regex used to determine if a commit is conventional'
    required: false
    default: "^(feat){1}(\([[:alnum:]._-]+\))?: ([[:alnum:]])+([[:space:][:print:]]*)"
  conventional-regex-major:
    description: 'Regex used to determine if a commit is conventional'
    required: false
    default: "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([[:alnum:]._-]+\))?(!): ([[:alnum:]])+([[:space:][:print:]]*)"

outputs:
  patch:
    description: "Count of patch commits"
    value: ${{ steps.commits.outputs.patch }}
  minor:
    description: "Count of minor commits"
    value: ${{ steps.commits.outputs.minor }}
  major:
    description: "Count of major commits"
    value: ${{ steps.commits.outputs.major }}


runs:
  using: "composite"
  steps:
    - name: "Check commits messages"
      id: commits
      run: |
        if [[ "" != $(git log --invert-grep --extended-regexp --grep=${{ inputs.conventional-regex }} ${{ inputs.git-range }}) ]]; then
          echo "The following commits message are invalid:"
          git log --oneline --invert-grep --extended-regexp --grep=${{ inputs.conventional-regex }} ${{ inputs.git-range }}
          exit 1
        fi

        echo patch=$(git log --oneline --extended-regexp --grep=${{ inputs.conventional-regex-patch }}  ${{ inputs.git-range }} | wc -l) >> $GITHUB_OUTPUT
        echo minor=$(git log --oneline --extended-regexp --grep=${{ inputs.conventional-regex-minor }} ${{ inputs.git-range }} | wc -l) >> $GITHUB_OUTPUT
        echo major=$(git log --oneline --extended-regexp --grep=${{ inputs.conventional-regex-major }} ${{ inputs.git-range }} | wc -l) >> $GITHUB_OUTPUT

      shell: bash