name: Check current commit
on: [pull_request]

jobs:
  dev:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: ${{ github.event.pull_request.commits }}
      - uses: bugbundle/commits@v1